name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint PR title with commitlint
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint
