name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    # Only run if this is a title change (edited event with title changes)
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || (github.event.action == 'edited' && github.event.changes.title))
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint PR title with commitlint
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint
